# fly.toml app configuration file generated for fretbuddy-z3uwxg on 2025-03-25T10:44:46Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "hsk-bot"
primary_region = "sin"  # Singapore region, you can change this to your preferred region

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_LEVEL = "INFO"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[deploy]
  strategy = "immediate"

[services.concurrency]
  hard_limit = 25
  soft_limit = 20
  type = "connections"

[services.resources]
  count = 1  # This explicitly sets the number of machines